### PR TITLE
Fix ie11 support (Object.values)

### PR DESCRIPTION
**Pull request by jdlehman**
Looks like ie11 doesn't support `Object.values`. I've replaced the 2 instances of this with code that will run in ie11.

My branch includes changes from running `npm run build`, let me know if you'd rather me commit the changes without the build changes, or if there are any other changes you want me to make.

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Arh, good spot, I thought I'd checked that on caniuse, but it appears not.

**Comment by davidjbradshaw** [comment]
I'll check and release this in the morning

**Comment by davidjbradshaw** [comment]
Released as v4.1.1

**Comment by davidjbradshaw** [comment]
Thank you for this

**Comment by jdlehman** [comment]
Thanks for the quick merge and release!

**Comment by reubenrd** [comment]
Your latest merge doesn't seem to be working for me - the iframe no longer resizes in any browser...  Also, I believe there are few out-of-date files in the repository.

**Comment by davidjbradshaw** [comment]
Any error message?

**Pull request merged**
