### PR TITLE
Updated checkOrigin setting documentation

### PR DESCRIPTION
**Pull request by euangoddard**
If custom URLs are used they must be specified by URL - not by domain

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Hmm interesting point. It's protocol + domain + port that is needed rather than URL. You right saying domains here isn't correct, but whilst URLs is better it is still maybe not the correct thing either. Interested in any further thoughts you have.

**Comment by davidjbradshaw** [comment]
Also interested in any other thoughts you have on the documentation. Are all the options clear or is the full list a bit overwhelming?

**Comment by euangoddard** [comment]
With regard to the documentation, it's been a while since I've read it fully. This `checkOrigin` option was new to me and I had to upgrade to take advantage of the array format. I would say that when I was setting this up I found the documentation very clear and well-laid out (same is true about the source code). I will be happy to have a read over the entire documentation and let you know how I find it if that would help.

Many thanks!

**Comment by davidjbradshaw** [comment]
Thank you, that would be very helpful. Version 3 adds a bunch of new options and I'm wondering if that makes it all a bit overwhelming for some people. 

Also I expect their are a few typos in it still.

**Comment by markvantilburg** [comment]
Maybe you can add a small note about upgrading to v3 from v2 in the documentation. 

E.g. is that an in place upgrade or are code changes required.

**Comment by euangoddard** [comment]
I've had a read and think that the documentation is well laid-out. There is no escaping the large number of options, but they are grouped sensibly and it's easy enough to find what you're looking for.

I didn't spot any typos or mistakes, but I'd have to use some of the other options to find out whether there is anything similar to the domain name/URL problem I spotted. Keep up the good work!

**Comment by davidjbradshaw** [comment]
@markvantilburg Good point, I've added a note in the dev channel docs for now. Basically the IE8 polyfil has changed and in v3 has it's own JS file, so you need to include that if upgrading.

@euangoddard Thanks for reading through everything.

**Comment by csmillie** [comment]
@davidjbradshaw I thought the option list was very clear.  I had to look around for some examples, specifically for some of the call backs...  I think including an example for most of them somewhere would help.

**Pull request merged**
