### PR TITLE
feat: vue composition api use

### PR DESCRIPTION
**Pull request by divine**
Can't test as it's a painfully hard to navigate the source?

Just some questions:
1. Where is the package.json file for the `@iframe-resizer/vue` ?
2. Vue version should be upgraded and require v3 at least.
3. Some options are like: `warningTimeout` simply being overwritten by to `:warning-timeout="0"` which should probably allowed somehow or changed?

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Hi,

You need to run the build script `npm run build:prod` and it will dynamically build the missing package.json file for you in the `dist/vue` folder.

Can you explain to me what this change does? This is the only thing I have ever built in Vue and don’t have a deep understanding of the platform.

Why does the Vue version need upgrading? Concerned that would be a breaking change, unless it never worked in 2.6.

How is `warningTimeout` getting overridden?

Cheers,
Dave.

**Comment by divine** [comment]
Hi,

> Can you explain to me what this change does? This is the only thing I have ever built in Vue and don’t have a deep understanding of the platform.

I have rewritten to use Composition API, see @ https://vuejs.org/guide/extras/composition-api-faq.html#why-composition-api

> Why does the Vue version need upgrading? Concerned that would be a breaking change, unless it never worked in 2.6.

Vue 2 has reached EOL and is no longer actively maintained. [Upgrade to Vue 3](https://vuejs.org/) or learn more about [Vue 2 EOL](https://v2.vuejs.org/eol/).

> How is `warningTimeout` getting overridden?

I was trying to add  `warningTimeout` to remove some noise but ESlint in my current project overrides it to `:warning-timeout`. Vue components bindings should be in that format instead.

Thanks!

**Comment by divine** [comment]
Sadly, currently I don’t have time to debug rollup issue. Otherwise component is working fine.

**Comment by davidjbradshaw** [comment]
Thanks, I will take a look once I have shaken off the flu.

**Comment by divine** [comment]
I hope you’ll recover soon and will feel better every day.

Thanks!

**Comment by davidjbradshaw** [comment]
Moved to #1370

**Pull request closed without merging**
