### PR TITLE
adding support of array for checkOrigin parameter of iframeResizer

### PR DESCRIPTION
**Pull request by andrej2k**
Here is pull request for the adding support of domain arrays in checkOrigin parameter discussed on davidjbradshaw/iframe-resizer#199

Adding also *.min.js and *.map artefacts from grunt. Please discard them if not relevant.

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Hi,

Why did you close this? Is there a problem with it?

Could you remove the .min.js and .map file please. It will make it easier to merge that way.

Thanks,
Dave.

**Comment by andrej2k** [comment]
I noticed that there are some problems with tests. I'll check why tests are failing and will ask for another pull request withourt .min.js and .map files.

**Comment by davidjbradshaw** [comment]
Ok cool.

**Comment by davidjbradshaw** [comment]
Hey just wondering how your getting on with this, as had another Pull Request and would like to bundle them into one release if possible.

**Comment by andrej2k** [comment]
Hi David,
I've just submit another one pull request: #203

Cheers, Andrej

**Pull request closed without merging**
