### PR TITLE
Add webpack support

### PR DESCRIPTION
**Pull request by ssalat**
Added webpack module support.

### CODE REVIEW

**Comment by ssalat** [comment]
Tested and works:
```javascript
// Only iFrameResizer (host page)
import {iframeResizer} from 'iframe-resizer'
```
or
```javascript
// Only iframeResizerContentWindow (iframe)
import {iframeResizerContentWindow} from 'iframe-resizer'
```

**Comment by skedone** [comment]
+1

**Comment by elektronik2k5** [comment]
+1 I was going to submit a similar PR to do just that - thank you @ssalat :)

**Comment by davidjbradshaw** [comment]
Released v2.8.7. Thanks.

**Pull request merged**
