### PR TITLE
Allow non-element hashes in URLs.

### PR DESCRIPTION
**Pull request by ezzatron**
My attempt at a fix for #145. Also fixed a typo `jumpToTaget` -> `jumpToTarget`.

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Happy to take the fix to the function name, however try/catch is nasty. Does changing `checkLocationHash()` to this fix the issue?

		function checkLocationHash(){
			var hash = location.hash;

			if ('' !== hash && '#' !== hash && -1 === hash.indexOf('/')){
				findTarget(hash);
			}
		}

**Comment by ezzatron** [comment]
That would probably fix my issue, but I suspect it won't address other issues, like [leading digits](http://stackoverflow.com/questions/20306204/using-queryselector-with-ids-that-are-numbers), which is a shame.

I wonder if an escaping function for CSS selectors would alleviate the issue? There are a couple of implementations on NPM ([this one](https://github.com/mathiasbynens/cssesc) looks promising). Then all you'd have to do is not log an error when no matching element is found.

**Comment by davidjbradshaw** [comment]
That catches leading digits It only allows a string that starts with # followed by and alpha char and then allows numbers and '-'.

**Comment by davidjbradshaw** [comment]
If you can take the try catch out I'l include the typo fix, I'll add the above code and push out another release.

**Comment by ezzatron** [comment]
But element IDs *can* be just digits in HTML5, it's very permissive. From the [spec](http://www.w3.org/TR/html5/dom.html#the-id-attribute):

> The value must be unique amongst all the IDs in the element's home subtree and must contain at least one character. The value must not contain any space characters.
> 
> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

I think the CSS escaping way is unfortunately the only way to fix this "properly", because what you pass to `querySelector()` *has* to be a valid CSS selector, and in this case, specifically a CSS *identifier* (that cssesc library seems to support this).

So, to cover all your bases, you'd really have to URI decode the hash, CSS encode the result, and only then pass it to `querySelector()`.

I realize it's more of a pain in the ass, but it will prevent related issues in future. That said, it doesn't bother me, so long as I can make my problem go away :)

Out of interest, why does this library manually handle hashes anyway?

**Comment by davidjbradshaw** [comment]
Oh hadn't realised it had changed that much in 5, I was only using querySelect instead of getElementById as it saved stripping the hash from the front of the string. Will think about this a bit more.

The library does this because not all browsers handle in page links in an iFrame and it also makes links that are not in the iFrame bubble up.

**Comment by ezzatron** [comment]
Ah, true. And that's a good point, `getElementById()` is probably a much simpler solution. All you'd have to do is strip the leading hash and use `decodeURIComponent()` on the rest. I'll update this PR accordingly, and see if it comes out cleaner.

**Comment by davidjbradshaw** [comment]
OK cool, happy to take a PR for that.

**Comment by ezzatron** [comment]
Okay, new commit pushed. A few things about the changes:

- I had to manually extract the hash, rather than using `window.location.hash`, because it's inconsistent whether it is encoded or not across different browsers. `window.location.href` is *always* encoded and hence safer to use.
- The code checks for elements by ID and also by name. A quick test in Chrome confirmed that IDs take precedence over named elements, so that's the way I implemented it too.
- I changed the warnings previously issued when an in-page link could not be found to normal log messages, otherwise every hash link would trigger a warning.
- I have no idea how to go about adding tests for this stuff, I'm sorry. The test suite does pass, though.

I'm not at work right now, but when I get into work tomorrow morning I can at least verify that this works for my use case.

Any major concerns so far?

**Comment by davidjbradshaw** [comment]
That all looks great to me. I'll wait till you can test your use case.

**Comment by ezzatron** [comment]
Okay, this branch seems to work fine for my use case. I checked the hash link examples and they still seem to work as intended also. It would be awesome if you could double check that before merging, though.

**Pull request merged**
