### PR TITLE
Added 'omit' option for scrolling parameter

### PR DESCRIPTION
**Pull request by mryand**
Adds #581

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Hi,

Rather than add yet another config property , it would be simpler to an ‘omit’ option to the scrolling attribute.

```
case ‘omit’:
  break;
```

**Comment by mryand** [comment]
I was thinking it should account for the possibility that you'd want to set the `style` attribute to `hidden` without adding the `scrolling` attribute. 

 I'm not sure the `style` attribute is well supported, though -- my testing suggests that when you use `style="overflow:hidden;"` without iframe-resizer you still see scrollbars. So perhaps that doesn't matter much.

I'll test out the `case: 'omit'` approach and update the PR.

**Comment by mryand** [comment]
Ok, I've updated the PR to use the `omit` method. I also updated the docs to reflect this additional option.

**Comment by mryand** [comment]
I tried to get a test in but clearly I got something wrong. I'm not familiar with qunit (I'm not primarily a js dev if it's not obvious from my code) so it's probably something I missed. On my local machine when I grunt I'm getting an unrelated testing error even without this additional test, so it's hard for me to troubleshoot. Apologies.

**Comment by davidjbradshaw** [comment]
What is the error your seeing?

**Comment by davidjbradshaw** [comment]
Thanks released in v3.6.3

**Pull request merged**
