### PR TITLE
Issues #405 and #562

### PR DESCRIPTION
**Pull request by thomaspringle**
Moving the debounce of getPageInfo() to either send messages to all iframes or debounce the messages. No test created to ensure this yet - working on it.

### CODE REVIEW

**Comment by thomaspringle** [comment]
Stuck on PhantomJS: Can't trigger the resize-event in pre 2.0 version and if I'm using PhantomJS 2.0 the `/* istanbul ignore next */` tags aren't recognised which leads to lower code coverage of iframeResizer.contentWindow.js.

**Comment by davidjbradshaw** [comment]
Don't worry too much about the code coverage if the tags don't work in 2.0.

**Comment by davidjbradshaw** [comment]
How you getting on with this?

**Comment by thomaspringle** [comment]
I'm still struggling with coveralls + PhantomJS 2. 

In my last commit I upgraded to PhantomJS v2 again, I can't get the test to trigger the window.eventListeners in v1.
With the consequence that the contentWindow-tests get lower coverage (due to the ignore flags not working in PhantomJS v2).

I'm happy with iframeResizer.js + getPageInfoSpec.js.

**Comment by davidjbradshaw** [comment]
OK well lets just take the lower code coverage then. Thanks for trying so hard to get it to work.

**Comment by davidjbradshaw** [comment]
Thanks release as v3.6.0

**Comment by thomaspringle** [comment]
Thanks!

**Pull request merged**
