### PR TITLE
Update vue.md

### PR DESCRIPTION
**Pull request by AltairCA**
update to support typescript

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Don't both versions work in both TS and JS?

**Comment by AltairCA** [comment]
nope, It's complaining about the type definition not found.

**Comment by AltairCA** [comment]
I'm using VS Code

**Comment by davidjbradshaw** [comment]
Can we just have the new version, rather than both, then happy to merge

**Comment by AltairCA** [comment]
Thing is I don't know if this is works in javascript. The one I have added is for typescript

**Comment by davidjbradshaw** [comment]
It should be fine

**Comment by davidjbradshaw** [comment]
Thanks

**Pull request merged**
