### PR TITLE
Adding 'warningEnabled' option's to enable warning or not.

### PR DESCRIPTION
**Pull request by tgregoire**

### CODE REVIEW

**Comment by tgregoire** [comment]
@davidjbradshaw Is this solution fine with you ?
I tried to add some tests, but I only add a new default parameter as it was before and the build is still passing.
Thanks !

**Comment by davidjbradshaw** [comment]
Why do you want to suppress the warning messages? Normally you shouldn't see them anyway.

**Comment by tgregoire** [comment]
For our purpose we need to setup the library more than once with the same iFrameId to make the iframe properly resized So the console is pollute by setup's warnings.

**Comment by davidjbradshaw** [comment]
If you're adding and removing an iFrame with the same ID, you need to close
the iFrame with iFrameResizer first and then you don’t get the warnings.

**Pull request closed without merging**
