### PR TITLE
fix readDataFromParent  mouseEvents Boolean to strBool

### PR DESCRIPTION
**Pull request by tonyliving**
readDataFromParent mouseEvents Boolean to strBool

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
What is the reason for changing this?

**Comment by tonyliving** [comment]
Boolean("false") --> ture wrong
strBool("false")-->false  right

You can try to set in parent page

iframeResizer(
        {
         mouseEvents:false
        },
    document.getElementById("iframe")
      )

https://github.com/davidjbradshaw/iframe-resizer/blob/f0adaca23aa71e87c28546cbf32dd1fbcb6450ae/src/iframeResizer.contentWindow.js#L211

https://github.com/davidjbradshaw/iframe-resizer/blob/f0adaca23aa71e87c28546cbf32dd1fbcb6450ae/src/iframeResizer.contentWindow.js#L214

You can compare these two lines.What to do with boolean values

**Comment by tonyliving** [comment]
@davidjbradshaw

**Comment by davidjbradshaw** [comment]
Released as v4.3.4

Sorry for the delay, I have been very ill for the last year.

**Pull request merged**
