### PR TITLE
feat: child types

### PR DESCRIPTION
**Pull request by jlarmstrongiv**
I added a `.d.ts` file for the `@iframe-resizer/child` package.  

I moved the appropriate types from the parent package:
- `interface IFramePageOptions`
- `interface IFramePage`
- `interface PageInfo`

I ensured that the global properties are defined on the `window` object and exported the namespace.

I ensured the types are output in the `dist` folder and added the `types` property to the `package.json`.

I don’t have an easy way to test it, but if you publish another `rc` release, I can look at it again on Wednesday or Thursday.

The main thing I’m considering changing is the namespace names in parent and child (currently `iframeResizer`) to reflect their new package names `@iframe-resizer/child` and `@iframe-resizer/parent`.

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Yeah changing the name spaces would seem to make sense to me as well. 

My one other comment is do we need to somehow connect the IFramePage interface to `window.parentIframe`, as that is where those methods are called from.

**Comment by jlarmstrongiv** [comment]
Sounds good!  I am leaving tomorrow for another trip, but I can look at it later next week 🚗

**Comment by davidjbradshaw** [comment]
Reading the docs and looking at the React d.ts file I think we need to do

```ts
declare module '@iframe-resizer/parent' {
```
and

```ts
declare module '@iframe-resizer/child' {
```

it also then says

> A key feature of modules in TypeScript is that two different modules will never contribute names to the same scope. Because the consumer of a module decides what name to assign it, there’s no need to proactively wrap up the exported symbols in a namespace.

https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html

Which seems to suggest we should take the `namespaces` out and just export the types.

**Comment by davidjbradshaw** [comment]
I'm going to merge this and apply the changes. Flying a little blind, but think I have it figured out.

**Pull request merged**
