### PR TITLE
Fix issue 772; Use existing iframe DOM element instead of document.ge…

### PR DESCRIPTION
**Pull request by martinbelanger**
I'm not able to test with your automated tests.
I tried with jasmine and with qunit.

qunit in Chrome work, but shadowRoot not seems to be supported with PhantomJS.
with jasmine, even with the master code, the tests passed.

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
So are the tests in this PR doing anything?

**Comment by martinbelanger** [comment]
I kept the tests in case of you was willing to trying to fix it. 
But I think it's ok to not make any other tests, because your tests assure that all is working again.
I don't added a new feature but I make a bug fix when getElementById is impossible.

I'm actualy trying to test an invalid getElementById instead of trying to make shadowDom works.

**Comment by davidjbradshaw** [comment]
Ok can you take the tests out then if they are not doing anything, the change is small enough that I am happy if the current test pass with this ok

**Comment by martinbelanger** [comment]
> Ok can you take the tests out then if they are not doing anything, the change is small enough that I am happy if the current test pass with this ok

Done

**Pull request merged**
