### PR TITLE
fixed error TS2613: Module "@iframe-resizer/parent" has no default ex…

### PR DESCRIPTION
**Pull request by pompep**
…port.

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
Thanks for this, looking at the child types, it has the same issue, but I”m not sure what I should be exporting in that one as it relates to the global namespace. Do you have any advice on this?

https://github.com/davidjbradshaw/iframe-resizer/blob/master/packages/child/index.d.ts

**Comment by pompep** [comment]
The child module exports nothing so I think the current d.ts is doing right with global Window redeclaration. As a user you just have to include this d.ts somehow e.g. by listing it in tsconfig.json
```
...
"include": [
        "./node_modules/@iframe-resizer/child/iframe-resizer.child.d.ts"
  ],
...
```

**Comment by davidjbradshaw** [comment]
Thank you, that’s good to know. I will merge this and get a release out for tomorrow.

**Comment by davidjbradshaw** [comment]
Released as v5.0.2

**Pull request merged**
