### PR TITLE
docs: add Ember addon to README

### PR DESCRIPTION
**Pull request by alexlafroscia**
I put together an Ember addon today as an idiomatic example of how to integrate `iframe-resizer` with Ember.js. I figured it would be a good thing to mention in this project's `README` along with the other framework integration examples!

### CODE REVIEW

**Comment by davidjbradshaw** [comment]
It’s a great thing the add, but can you check the link as it 404s when I try it.

**Comment by davidjbradshaw** [comment]
Or is it currently a private repo?

**Comment by alexlafroscia** [comment]
Ah, it was! I didn't realize that GitHub is making repositories private by default with the `gh` command line tool these days.

It would be public now!

**Comment by davidjbradshaw** [comment]
Thanks

**Pull request merged**
